### ISSUE TITLE
2DのRPG用に作ったマップ（.json）が表示されない問題

### ISSUE THREAD

**Issue by KyoheiNakamura** [VisitSpace-com/Finance_RPG#1]
ぱっと見ですが JSON ファイルへのパスが間違ってるように見えます！

https://github.com/VisitSpace-com/Finance_RPG/blob/93f0079bc3dbe886eecb074d213c02dbcb66d827/lib/tax_office.dart#L11

以下のようにすると動くかもです！

```dart
const tilemap = 'assets/images/tax-office-tile.json'; 
```

**Comment by VisitSpace-com** [comment]
来なかったか。

<img width="1194" alt="browser" src="https://github.com/VisitSpace-com/Finance_RPG/assets/86555971/39c01827-236d-4a19-9d20-864a2a8fbc54">

<img width="549" alt="error" src="https://github.com/VisitSpace-com/Finance_RPG/assets/86555971/1bf51667-d7bc-4947-ab9a-0a6f8454fe42">
